### PR TITLE
feat: update structure deleting deprecated dependencies

### PR DESCRIPTION
**Pull request by kevinccbsg**
## Description

This PR updates this projects' dependencies. Some of this where:

- [X] Deprecated body parser
- [X] New husky version
- [X] Remove optimistic (package that is not being used)
- [X] Change OpenAPI library. We change It to `express-jsdoc-swagger` as it has better support.
- [X] Update the rest of the dependencies

We did this for the normal use case not the `--showcase`

## Types of changes

- [X] Documentation Update
- [X] Other (if none of the other choices apply)

## How to review this PR

I would recommend downloading this branch generator and test in your local branch.

### CODE REVIEW

**Comment by MatteoDiPaolo** [comment]
@kevinccbsg can we review this PR in a quick call?

**Comment by kevinccbsg** [comment]
> @kevinccbsg can we review this PR in a quick call?

@MatteoDiPaolo just let me know when and I'll be glad to jump in a call 😄

**Review by MatteoDiPaolo — COMMENTED** [review]
* the file `docs/syncapi.yaml` is no longer needed
* the endpoints `/__/manifest` in the `components/routes/admin-routes.js`file should be better documented as it was thanks to the file `docs/syncapi.yaml`
  * you need to have in place the file `components/routes/spec-routes.js` please refer to [spec-routes.js](https://github.com/infinitaslearning/service-shop-integrations-adapter/blob/master/components/routes/spec-routes.js) and [admin-routes.js](https://github.com/infinitaslearning/service-shop-integrations-adapter/blob/master/components/routes/admin-routes.js)
  * the same goes for the files
    * `generators/app/templates/lib/components/routes/v1/api-routes.js`
    * `generators/app/templates/lib/components/routes/v2/api-routes.js`

**Comment by kevinccbsg** [comment]
I would love to get rid of Travis 😅 

Screenshot 2021-06-17 at 21 44 22

**Comment by kevinccbsg** [comment]
There you go, docs with `express-jsdoc-swagger`

Screenshot 2021-06-17 at 23 49 36

**Review by MatteoDiPaolo — APPROVED** [review]
lgtm

**Pull request merged**
