### PR TITLE
Upgrade template

### LINKED ISSUE #19: Upgrade template
### Let's update dependencies
- [x] Update to Node 12
- [x] Update dependencies
Captura de pantalla 2019-11-29 a las 9 37 36

### PR DESCRIPTION
**Pull request by UlisesGascon**
### Main Changes
- Generated project will use Node v12 by default (NVM)
- Migrated to new Husky Syntaxis (Since version 2)
- Dependencies upgraded:
```
 on-headers                  ^1.0.1  →   ^1.0.2 
 body-parser                ^1.15.2  →  ^1.19.0 
 boom                        ^3.2.2  →   ^7.3.0 
 bunyan                      ^1.8.5  →  ^1.8.12 
 chalk                       ^1.1.3  →   ^3.0.0 
 confabulous                 ^1.1.0  →   ^1.7.0 
 debug                       ^2.2.0  →   ^4.1.1 
 optional                    ^0.1.3  →   ^0.1.4 
 prepper                     ^1.1.0  →   ^1.2.0 
 systemic                    ^3.0.0  →   ^3.3.0 
 systemic-express            ^1.1.0  →   ^1.1.1 
 eslint                     ^4.19.1  →   ^6.7.1 
 eslint-config-airbnb-base  ^11.3.2  →  ^14.0.0 
 eslint-plugin-import       ^2.14.0  →  ^2.18.2 
 eslint-plugin-mocha         ^5.2.0  →   ^6.2.2 
 husky                       ^1.1.0  →   ^3.1.0 
 mocha                       ^5.2.0  →   ^6.2.2 
 mocha-junit-reporter       ^1.18.0  →  ^1.23.1 
 sinon                       ^7.3.2  →   ^7.5.0 
 supertest                   ^3.0.0  →   ^4.0.2 
```

### Context
- ⚠️ Close #19 
- FYI @kevinccbsg @MatteoDiPaolo @inigomarquinez @Betisman 

### Changelog
- 3a88bf2 Upgrade to Node 12 by @UlisesGascon
- 86de8e7 Upgraded dependencies to latests version by @UlisesGascon

### CODE REVIEW

**Comment by Betisman** [comment]
The build breaks in the CI.
I've seen the matrix we have set in Travis is defined in this file https://github.com/guidesmiths/generator-systemic/blob/master/.travis.yml and it's just for node versions from 4 to 8. Shouldn't we update it?

**Comment by UlisesGascon** [comment]
Thanks @Betisman! The CI was broken on master already. I just fixed it in #22 ;-)

**Comment by UlisesGascon** [comment]
As agreed I will merge it 👍

**Comment by UlisesGascon** [comment]
This will be release 2.1.1

**Pull request merged**
